development:
  adapter: postgresql
  encoding: unicode
  database: hellorails_dev
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hellorails_test
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: hellorails
  pool: 5
  username: postgres
  password: kitten8184
  host: localhost